### ISSUE TITLE
Crash on startup on device with API < 29

### ISSUE THREAD

**Issue by OHermesJunior** [CraZyLegenD/Crashy#1]
Not sure why this is being called on device with API < 29, but the provider crashes the app on startup:
https://github.com/CraZyLegenD/Crashy/blob/28c11a0f68c8afffc5b809321d7fc531809bced0/crashyreporter/src/main/java/com/crazylegend/crashyreporter/extensions/ExtensionFunctions.kt#L65-L66

```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.NoSuchMethodError: No virtual method getCurrentThermalStatus()I in class Landroid/os/PowerManager; or its super classes (declaration of 'android.os.PowerManager' appears in /system/framework/framework.jar!classes2.dex)
```

**Comment by FunkyMuse** [comment]
It crashes because the thermal manager was added on API >= 29.
It's fixed with [1.0.4](https://github.com/CraZyLegenD/Crashy/releases/tag/1.0.4)
