### ISSUE TITLE
No crash log even after a crash

### ISSUE THREAD

**Issue by Docile-Alligator** [CraZyLegenD/Crashy#3]
It doesn't have any log.

**Comment by Docile-Alligator** [comment]
Do I need to manually log every crash log first?

**Comment by FunkyMuse** [comment]
```
dependencies {
    // androidX startup for auto-init
    implementation "androidx.startup:startup-runtime:1.0.0-alpha01"

    //crashy
    implementation 'com.github.CraZyLegenD:Crashy:1.0.5'
  }

```
And inside your manifest

```
 <provider
   android:name="androidx.startup.InitializationProvider"
   android:authorities="${applicationId}.androidx-startup"
   android:exported="false"
   tools:node="merge">
       <meta-data
          android:name="com.crazylegend.crashyreporter.initializer.CrashyInitializer"
          android:value="androidx.startup" />
</provider>

```
Do you have that?

**Comment by Docile-Alligator** [comment]
Yes I have that.

**Comment by FunkyMuse** [comment]
Then I can't help you if you don't post code sample or project.
Once the crash happened it'll log it, if it was an exception thrown you have to manually log it.

Please kindly post a project sample so that I can look into the issue you're having.

**Comment by Docile-Alligator** [comment]
This is the project: https://github.com/Docile-Alligator/Infinity-For-Reddit

manifest: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/685a39ba58fab82cc0486e49394a0f398bba8254/app/src/main/AndroidManifest.xml#L330

build.gradle: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/685a39ba58fab82cc0486e49394a0f398bba8254/app/build.gradle#L97

Fragment for showing crash reports: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/master/app/src/main/java/ml/docilealligator/infinityforreddit/Settings/CrashReportsFragment.java

Adapter for showing crash reports: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/master/app/src/main/java/ml/docilealligator/infinityforreddit/Settings/CrashReportsRecyclerViewAdapter.java

Thank you!

**Comment by FunkyMuse** [comment]
> This is the project: https://github.com/Docile-Alligator/Infinity-For-Reddit
> 
> manifest: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/685a39ba58fab82cc0486e49394a0f398bba8254/app/src/main/AndroidManifest.xml#L330
> 
> build.gradle: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/685a39ba58fab82cc0486e49394a0f398bba8254/app/build.gradle#L97
> 
> Fragment for showing crash reports: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/master/app/src/main/java/ml/docilealligator/infinityforreddit/Settings/CrashReportsFragment.java
> 
> Adapter for showing crash reports: https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/master/app/src/main/java/ml/docilealligator/infinityforreddit/Settings/CrashReportsRecyclerViewAdapter.java
> 
> Thank you!

Is there a section where it crashes and the crash isn't caught or i should force a crash to test it?

**Comment by Docile-Alligator** [comment]
You need to force a crash :)

**Comment by Docile-Alligator** [comment]
There is a crash in minifiedRelesase though. If you like I can send a signed apk to you.

**Comment by Docile-Alligator** [comment]
Here it is: https://drive.google.com/file/d/1-gdPp-IzDA4HRQRG2TpIybWMcO5X251_/view?usp=sharing

Go to Settings->Interface->Font->Font Preview and the app will crash

**Comment by FunkyMuse** [comment]
I see that the project is written in Java and the library is in Kotlin, I'm not sure how inlining works in Java since the library relies on inlined functions.

Can you try adding

```
compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

```

I think you can ommit the Kotlin options

**Comment by Docile-Alligator** [comment]
Thank you. I have added compileOptions already in https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/685a39ba58fab82cc0486e49394a0f398bba8254/app/build.gradle#L31

But adding kotlinkOptions will give me an error when syncing the project.

**Comment by FunkyMuse** [comment]
> Thank you. I have added compileOptions already in https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/685a39ba58fab82cc0486e49394a0f398bba8254/app/build.gradle#L31
> 
> But adding kotlinkOptions will give me an error when syncing the project.

The kotlin options are for kotlin project that's why i said you can omit them.

So... Does it work now?

**Comment by Docile-Alligator** [comment]
No, it doesn't. It's weird.

**Comment by FunkyMuse** [comment]
I didn't notice that the project was Java, my bad, the library won't work with Java, probably I should've mentioned that somewhere.
Sorry for your inconvenience, maybe convert to Kotlin, I've seen the code and it'll benefit a lot from Kotlin?

**Comment by Docile-Alligator** [comment]
No problem! I will learn Kotlin first. :)

**Comment by FunkyMuse** [comment]
> No problem! I will learn Kotlin first. :)

Can you check if 1.0.6 works for you?
I think it was mistake on my end...
Sorry.

**Comment by FunkyMuse** [comment]
> No problem! I will learn Kotlin first. :)

If you decide to check out the new version let me know, I'll be closing the issue due to inactivity.

**Comment by Docile-Alligator** [comment]
Oh! Sorry for the very late reply! Didn't check my inbox. It works perfectly fine now! Thank you for this amazing library!
